Add support for the OV5640 to the Arduino Portenta
openmv/openmv pull request #1195
Opened 2021-02-28 18:03 UTC by kwagyeman

2021-02-28 18:25 UTC, iabdalkader requested changes

2021-02-28 18:25 UTC, iabdalkader commented on src/omv/sensors/ov5640.h
> +#endif
```suggestion
```
Define in omv_boardconfig.h or switch all to 20MHz.

2021-02-28 18:25 UTC, iabdalkader commented on src/omv/boards/PORTENTA/omv_boardconfig.h
> +#define OMV_ENABLE_OV2640       (1)
```suggestion
#define OMV_ENABLE_OV2640       (0)
```

2021-02-28 18:25 UTC, iabdalkader commented on src/omv/sensors/ov5640.c
> +    #else
```suggestion
    #if (OV5640_XCLK_FREQ==20000000)
    { 0x30, 0x37, 0x12 },
    { 0x30, 0x36, 0x46 },
    #else
```

2021-02-28 18:25 UTC, iabdalkader commented on src/omv/sensors/ov5640.c
> +    #if defined(MCU_SERIES_H7) && (!defined(PORTENTA))
```suggestion
    #if defined(MCU_SERIES_H7) && (OV5640_XCLK_FREQ == 24000000)
```

2021-05-31 02:28 UTC, kwagyeman commented
Work in progress commit. Restructured code to meet previous comments. Everything is defined in headers now.

That said, OV5640 camera appears to pass probe and the clock is set to the right freq... however, all I2C accesses after the probe fail. Not sure what's wrong. Will need to debug later after reviewing new designs.

2022-01-16 23:26 UTC, kwagyeman commented
This is mergeable now. Portena OV5640 works at 30 FPS.

2022-01-21 04:38 UTC, kwagyeman commented
Merge please.

2022-01-22 20:57 UTC, merged

2025-01-30 05:10 UTC, iabdalkader commented
This pull request has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/portenta-better-camera/10565/5