MDMA kinda working
openmv/openmv pull request #1271
Opened 2021-04-21 17:36 UTC by kwagyeman

Working through issues and testing.

MT9V034 crashes:

```
import sensor, image, time, pyb

sensor.reset()
sensor.set_pixformat(sensor.GRAYSCALE)
sensor.set_framesize(sensor.VGA)
sensor.set_framebuffers(2)
clock = time.clock()
while(True):
    clock.tick()
    img = sensor.snapshot()
    print(clock.fps())
```

Trace of calls shows this before lockup:

HAL_MDMA_Start_IT start
DCMI_DMAConvCpltUser abort
DCMI_MDMA_XFER_CPLT_CB abort

>> DCMI_DMAConvCpltUser abort
>> DCMI_MDMA_XFER_CPLT_CB abort

Shouldn't have been called in this order. 

...

Looks like interrupt priority inversion is happening. Will fix.

2021-04-25 18:48 UTC, iabdalkader commented
Have a few improvements:
1) We can merge the two paths in  `void DCMI_DMAConvCpltUser(uint32_t addr)` and replace with this:
If you'd like to avoid branches in unaligned_memcpy, we can add new set of functions `unaligned_memcpy_colwise_xx`

```
switch (sensor.pixformat) {
    case PIXFORMAT_BAYER:
        dst += buffer->offset * (sensor.transpose) ? 1 : MAIN_FB()->u;
        src += MAIN_FB()->x;
        #if (OMV_ENABLE_SENSOR_MDMA == 1)
        mdma_memcpy(buffer, dst, src, sizeof(uint8_t), sensor.transpose);
        #else
        unaligned_memcpy(dst, src, MAIN_FB()->u, MAIN_FB()->v, sensor.transpose);
        #endif
        break;
    case PIXFORMAT_GRAYSCALE:
        dst += buffer->offset * (sensor.transpose) ? 1 : MAIN_FB()->u;
        if (sensor.gs_bpp == sizeof(uint8_t)) {
            // 1BPP GRAYSCALE.
            src += MAIN_FB()->x;
            #if (OMV_ENABLE_SENSOR_MDMA == 1)
            mdma_memcpy(buffer, dst, src, sizeof(uint8_t), sensor.transpose);
            #else
            unaligned_memcpy(dst, src, MAIN_FB()->u, MAIN_FB()->v, sensor.transpose);
            #endif
        } else {
            // Extract Y channel from YUV.
            src16 += MAIN_FB()->x;
            #if (OMV_ENABLE_SENSOR_MDMA == 1)
            mdma_memcpy(buffer, dst, src16, sizeof(uint8_t), sensor.transpose);
            #else
            unaligned_2_to_1_memcpy(dst, src16, MAIN_FB()->u, MAIN_FB()->v, sensor.transpose);
            #endif
        }
        break;
    case PIXFORMAT_RGB565:
    case PIXFORMAT_YUV422:
        dst16 += buffer->offset * (sensor.transpose) ? 1 : MAIN_FB()->u;
        src16 += MAIN_FB()->x;
        #if (OMV_ENABLE_SENSOR_MDMA == 1)
        mdma_memcpy(buffer, dst16, src16, sizeof(uint16_t), sensor.transpose);
        #else
        if (SENSOR_HW_FLAGS_GET(&sensor, SWNSOR_HW_FLAGS_RGB565_REV)) {
            unaligned_memcpy_rev16(dst16, src16, MAIN_FB()->u, MAIN_FB()->v, sensor.transpose);
        } else {
            unaligned_memcpy(dst16, src16, MAIN_FB()->u * sizeof(uint16_t), MAIN_FB()->v, sensor.transpose);
        }
        #endif
        break;
    default:
        break;
}
```

2) In snapshot that's really a lot to do in one function, all the MDMA setup should be moved to a new function.

```
#if (OMV_ENABLE_SENSOR_MDMA == 1)
int mdma_config(sensor_t *sensor, uint32_t line_width_bytes, bytes_per_pixel, etc...)
{
}
#endif
```
3) The long if else chains (for source/dest inc, size burst etc..) should be replaced by either this (note the size is just bits from 0->n shifted by Pos):
```
DCMI_MDMA_Handle0.Init.SourceBurst  = MDMA_SOURCE_BURST_SINGLE;
DCMI_MDMA_Handle0.Init.DestBurst    = MDMA_DEST_BURST_SINGLE;
for (uint32_t i=7; i>0; i--) {
    if ((buffer_transfer_burst_size % (2<<(i-1))) == 0) {
        DCMI_MDMA_Handle0.Init.SourceBurst  = i << MDMA_CTCR_SBURST_Pos;
        DCMI_MDMA_Handle0.Init.DestBurst    = i << MDMA_CTCR_DBURST_Pos;
        break;
    }
}
```
Or just const lookup tables:
```
static const uint32_t MDMA_BURST_SIZE[][2] = {
         {MDMA_SOURCE_BURST_SINGLE, MDMA_DEST_BURST_SINGLE},
         {MDMA_SOURCE_BURST_2BEATS, MDMA_DEST_BURST_2BEATS},
         .....
};

DCMI_MDMA_Handle0.Init.SourceBurst  = MDMA_BURST_SIZE[0][0];
DCMI_MDMA_Handle0.Init.DestBurst      = MDMA_BURST_SIZE[0][1];
for (uint32_t i=7; i>0; i--) {
    if ((buffer_transfer_burst_size % (2<<(i-1))) == 0) {
        DCMI_MDMA_Handle0.Init.SourceBurst  = MDMA_BURST_SIZE[i][0];
        DCMI_MDMA_Handle0.Init.DestBurst      = MDMA_BURST_SIZE[i][1];
        break;
    }
}
```

2021-04-28 05:33 UTC, kwagyeman commented
Okay, I've done 2 and 3. Just need to redo 1.

2021-04-30 05:42 UTC, kwagyeman commented
Done with everything. Just need to test on all cameras with all camera sensors.

2021-04-30 16:37 UTC, kwagyeman commented
Checked all cameras. This is ready to be merged.

2021-05-01 18:24 UTC, iabdalkader requested changes

2021-05-01 18:24 UTC, iabdalkader commented on src/omv/ports/stm32/sensor.c
> +MDMA_HandleTypeDef DCMI_MDMA_Handle1 = {.Instance = MDMA_Channel1};
```suggestion
static MDMA_HandleTypeDef DCMI_MDMA_Handle0 = {.Instance = MDMA_Channel0};
static MDMA_HandleTypeDef DCMI_MDMA_Handle1 = {.Instance = MDMA_Channel1};
```

2021-05-01 18:24 UTC, iabdalkader commented on src/omv/ports/stm32/sensor.c
> +void mdma_memcpy(vbuffer_t *buffer, void *dst, void *src, int bpp, bool transposed)
```suggestion
static void mdma_memcpy(vbuffer_t *buffer, void *dst, void *src, int bpp, bool transposed)
```

2021-05-01 18:24 UTC, iabdalkader commented on src/omv/ports/stm32/sensor.c
> +uint32_t get_dcmi_hw_crop(uint32_t bytes_per_pixel)
```suggestion
static uint32_t get_dcmi_hw_crop(uint32_t bytes_per_pixel)
```

2021-05-01 18:24 UTC, iabdalkader commented on src/omv/ports/stm32/sensor.c
> +void mdma_config(MDMA_InitTypeDef *init, sensor_t *sensor, uint32_t bytes_per_pixel)
```suggestion
static void mdma_config(MDMA_InitTypeDef *init, sensor_t *sensor, uint32_t bytes_per_pixel)
```

2021-05-01 18:25 UTC, iabdalkader approved these changes

2021-05-01 18:53 UTC, merged