Reorganize the ISC SPI related handles/macros.
openmv/openmv pull request #1360
Opened 2021-06-11 06:33 UTC by Lak4CYUT

The SPI bus on image sensor connector is not design for Lepton sensor only.
Thereforce, change the related functions and macros name from LEPTON_SPI_*
to ISC_SPI_* and move interrupt callback to sensor.c.

2021-06-11 15:35 UTC, iabdalkader requested changes

2021-06-11 15:35 UTC, iabdalkader commented on src/omv/ports/stm32/sensor.c
> +
```suggestion
#ifdef ISC_SPI
SPI_HandleTypeDef ISC_SPIHandle = {.Instance = ISC_SPI};
#endif // ISC_SPI

```

2021-06-11 21:20 UTC, iabdalkader commented
@Lak4CYUT Looks good! Just need the above small change, the handle shouldn't be declared if nothing is using it.

2021-06-12 01:09 UTC, Lak4CYUT commented
> @Lak4CYUT Looks good! Just need the above small change, the handle shouldn't be declared if nothing is using it.

Ya, it is. But if we do so, every driver which rely on ISC_SPI must be check both #ifdef ISC_SPI and OMV_ENABLE_XXX.
Because it may cause a compiler time error.

2021-06-12 12:02 UTC, iabdalkader commented
> Ya, it is. But if we do so, every driver which rely on ISC_SPI must be check both #ifdef ISC_SPI and OMV_ENABLE_XXX.
> Because it may cause a compiler time error, are you sure u want to do it?

Yes it's okay, and you don't need to for ISC_SPI anywhere else, if you enable an SPI sensor without defining ISC_SPI it should cause an error so you know that something is wrong.

2021-06-12 13:56 UTC, merged

2021-06-12 14:18 UTC, iabdalkader commented
@Lak4CYUT merged, thanks! You should send the PR that adds the driver next (all the Makefiles changes, all omv/drivers/pixart/* and omv/sensors/paj6100*), followed by a PR with changes to sensor.h and sensor.c. Finally a PR to enable it in omv_boardconfig.h

2021-06-12 16:37 UTC, Lak4CYUT commented
> Yes it's okay, and you don't need to check for ISC_SPI anywhere else, if you enable an SPI sensor without defining ISC_SPI it should cause an error so you know that something is wrong. Currently it will define an empty handle (with a NULL instance) and no IRQ/DMA handlers which will cause faults if you run it.

Wow, agree that. It is a good point.
I will send the next PR later, see you soon.