Add docker build
openmv/openmv pull request #1375
Opened 2021-06-22 17:07 UTC by galal-hussein

2021-06-22 18:02 UTC, iabdalkader requested changes
Please move all new files to openmv/docker/ so it's all contained in there. You'll need to update the build script, gitignore and README, the layout/filenames should look like this:
```
openmv/docker/Makefile
openmv/docker/dockerfile
openmv/docker/build.sh
```
Note: You should probably set a `TOP_DIR` variable to `../` (in Makefile or the build script) and you can use `-C` with git to run the command in a different dir, for example:

```
TOP_DIR = ../
git -C $(TOP_DIR)/src/micropython/ submodule update --init --depth=1
```

Do we really need the build script ? If not you can just put the commands in the Makefile.

2021-06-23 00:36 UTC, galal-hussein commented on scripts/build
> +git -C src/micropython/ submodule update --init --depth=1
fixed

2021-06-23 00:37 UTC, galal-hussein commented on src/README.md
> +git clone https://github.com/openmv/openmv.git
fixed

2021-06-23 00:37 UTC, galal-hussein commented on src/README.md
> +
fixed

2021-06-23 15:01 UTC, iabdalkader approved these changes

2021-06-23 15:01 UTC, merged