modules/py_tf: Fix non-square image support.
openmv/openmv pull request #2031
Opened 2023-11-27 04:26 UTC by kwagyeman

Non-square image support has not been working for a long time. This forum post pointed out the issue: https://forums.openmv.io/t/edge-impulse-result-wrong-on-openmv-h7-plus/8968/3.

Code is now updated to use the new draw image scaling and centering logic. This applies for classification and segmentation/detect.

Then segmentation has been updated to locate the final result in the right location given all the scaling and cropping going on when your image aspect ratio does not match the CNN aspect ratio.

2023-12-03 08:59 UTC, iabdalkader requested changes

2023-12-03 08:59 UTC, iabdalkader commented on src/omv/modules/py_tf.c
> +        // MAX == KeepAspectRationByExpanding - MIN == KeepAspectRatio
```suggestion
        // MAX == KeepAspectRatioByExpanding - MIN == KeepAspectRatio
```

2023-12-03 08:59 UTC, iabdalkader commented on src/omv/modules/py_tf.c
> +        int y_offset = fast_floorf((roi.h - (img->h * scale)) / 2.f) + roi.y;
```suggestion
        int x_offset = fast_floorf((roi.w - (img->w * scale)) / 2.0f) + roi.x;
        int y_offset = fast_floorf((roi.h - (img->h * scale)) / 2.0f) + roi.y;
```

2023-12-04 03:41 UTC, kwagyeman commented on src/omv/modules/py_tf.c
> +        int y_offset = fast_floorf((roi.h - (img->h * scale)) / 2.f) + roi.y;
Fixed

2023-12-04 19:02 UTC, merged