imlib/draw: Add anti aliasing in draw_ellipse
openmv/openmv pull request #2124
Opened 2024-02-01 10:04 UTC by xue-singtown

Hi, I add anti aliasing feature in draw_line method. I tested Binary, Grayscale and RGB565 format.

Reference code: https://gist.github.com/randvoorhies/807ce6e20840ab5314eb7c547899de68

test code in OpenMV Cam:

```
import sensor
sensor.reset() 
sensor.set_pixformat(sensor.RGB565)
sensor.set_framesize(sensor.QVGA)
sensor.skip_frames(time=2000)

a = 11
b = 60
angle = 30

while True:
    img = sensor.snapshot()

    img.draw_ellipse(50, 80, a, b, angle, fill=False, color=(255, 0, 0), thickness=1)
    img.draw_ellipse(100, 80, a, b, angle, fill=False, color=(255, 0, 0), thickness=5)
    img.draw_ellipse(150, 80, a, b, angle, fill=True, color=(255, 0, 0), thickness=5)

```
![img_degree_30](https://github.com/openmv/openmv/assets/156400698/e45be8c6-6328-49ae-a419-8cae7f28b0d8)

# Known issue

There are drawing errors in draw ellipse with width:
1. There will be extra pixels at the corners.
2. It will become a straight line at a certain angle.

![img_degree_17](https://github.com/openmv/openmv/assets/156400698/120178db-38f7-4f2d-b14b-e50ce0a70a3b)

Note: the function of drawing an ellipse with a line width of 1 and the function of drawing a line width of other than 1 are two functions. Thickness = 1 is perfect.

I've been researching for a few days and can't figure this out. If you guys can figure it out, I can help.

2024-02-02 14:34 UTC, iabdalkader commented
Please fix the comments, they should start with a capital letter, end with a ".".
```diff
-// plot ellipse rotated by angle (degree)  👎🏼 
+// Plot ellipse rotated by angle (degree). 👍🏼 
```

2024-04-01 16:13 UTC, iabdalkader requested changes
Please avoid multiple variable definitions, function calls, and assignments on a single line. I fixed a few examples, but there are more in code.

2024-04-01 16:13 UTC, iabdalkader commented on src/omv/imlib/draw.c
> +            f = (2 * err + dy < 0);
```suggestion
            bool f = (2 * err + dy < 0);
```

2024-04-01 16:13 UTC, iabdalkader commented on src/omv/imlib/draw.c
> +            return plot_quad_rational_bezier_width_seg(img, sx, sy, dx, dy, x2, y2, cur, c, th);
```suggestion
            cur = (w + 1.0) / 2.0;
            w = fast_sqrtf(w);
            xy = 1.0 / (w + 1.0);
            sx = fast_floorf((x0 + 2.0 * w * x1 + x2) * xy / 2.0 + 0.5); // Subdivide curve.
            sy = fast_floorf((y0 + 2.0 * w * y1 + y2) * xy / 2.0 + 0.5); // Plot separately.
            dx = fast_floorf((w * x1 + x0) * xy + 0.5);
            dy = fast_floorf((y1 * w + y0) * xy + 0.5);
            plot_quad_rational_bezier_width_seg(img, x0, y0, dx, dy, sx, sy, cur, c, th);
            dx = fast_floorf((w * x1 + x2) * xy + 0.5);
            dy = fast_floorf((y1 * w + y2) * xy + 0.5);
            return plot_quad_rational_bezier_width_seg(img, sx, sy, dx, dy, x2, y2, cur, c, th);
```

2024-04-01 16:13 UTC, iabdalkader commented on src/omv/imlib/draw.c
> +
```suggestion
```

2024-04-01 16:13 UTC, iabdalkader commented on src/omv/imlib/draw.c
> +                    x0 += sx; dx += xy; err += dy; dy += yy;        // X step.
```suggestion
                    // X step.
                    x0 += sx;
                    dx += xy;
                    err += dy;
                    dy += yy;
```

2024-04-01 16:13 UTC, iabdalkader commented on src/omv/imlib/draw.c
> +            xx = -xx; yy = -yy; cur = -cur; xy = -xy;
```suggestion
            xx = -xx;
            yy = -yy;
            cur = -cur;
            xy = -xy;
```

2024-04-02 03:30 UTC, kwagyeman commented
@xue-singtown @iabdalkader - I'll see if I can process this PR this week.

2024-04-06 03:25 UTC, kwagyeman commented
@xue-singtown - I am working on fixing this PR now.

2024-04-14 01:45 UTC, kwagyeman commented
Replaced by https://github.com/openmv/openmv/pull/2195.

2024-04-14 01:45 UTC, closed without merging

2024-04-14 01:47 UTC, kwagyeman reviewed
Replaced by: https://github.com/openmv/openmv/pull/2195

I managed to add fill support natively to the code. I don't quite see how to fix the weird graphical glitches it has when changing from steep to flat and vice versus curves.