scripts/examples: Add imxrt board control examples.
openmv/openmv pull request #2149
Opened 2024-02-14 01:32 UTC by kwagyeman

2024-02-15 20:49 UTC, iabdalkader commented
This pull request has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/openmv-cam-rt1062-examples-and-pyb/9217/2

2024-02-16 08:05 UTC, iabdalkader requested changes
Can you please combine `pin_read.py` and `pin_write.py` in a simple `pin_control.py` example like other boards ? Let's keep those examples basic.

2024-02-16 08:05 UTC, iabdalkader commented on scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/spi_control.py
> +# the LCD shield to run this example.
Typo.

```suggestion
# This example shows how to use the SPI bus to directly control the LCD shield without
# using the built-in LCD driver. You will need the LCD shield to run this example.
```

2024-02-16 08:05 UTC, iabdalkader commented on scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/spi_loopback.py
> +        i = 0
```suggestion
```

2024-02-16 08:05 UTC, iabdalkader commented on scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/uart_loopback.py
> +    time.sleep_ms(100)
```suggestion
```

2024-02-16 19:55 UTC, kwagyeman commented on scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/spi_control.py
> +# the LCD shield to run this example.
Fixed

2024-02-16 19:55 UTC, kwagyeman commented on scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/spi_loopback.py
> +        i = 0
Done

2024-02-16 19:55 UTC, kwagyeman commented on scripts/examples/50-OpenMV-Boards/50-IMXRT-Boards/50-Board-Control/uart_loopback.py
> +    time.sleep_ms(100)
Done

2024-02-16 20:02 UTC, kwagyeman commented
@iabdalkader Updated.

2024-02-17 07:39 UTC, iabdalkader approved these changes

2024-02-17 07:39 UTC, merged