Support PixArt image sensor PAG7920
openmv/openmv pull request #2199
Opened 2024-04-16 02:15 UTC by Lak4CYUT

1. Add a sensor driver for PAG7920.
2. Add PAG7920-related definitions.

2024-04-16 02:28 UTC, kwagyeman commented
@Lak4CYUT - I have one of these sensors. I can test this PR after all review comments are addressed from me and @iabdalkader.

2024-04-16 13:14 UTC, iabdalkader requested changes

2024-04-16 13:14 UTC, iabdalkader commented on src/omv/sensors/pag7920_reg.h
> +const uint16_t GRAY_QVGA [] = {
```suggestion
const uint16_t GRAY_QVGA [] = {
```
We typically put register arrays in the `*.c` files, just for consistency.  Also they're typically 2D arrays, with `0x00`, or `0xFF`, marking the end of the array. For example:
```c
static const uint8_t qvga_regs[][2] = {
    { COM3,         0x00 },
    ....
    { 0xFF,         0xFF },
};
....
    for (int i = 0; qvga_regs[i][0] != 0xFF; i++) {
        ret |= omv_i2c_writeb(&sensor->i2c_bus, sensor->slv_addr, regs[i][0], regs[i][1]);
    }
```

2024-04-16 13:14 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +#if (SENSOR_I2C_DEBUG == 1)
```suggestion
    #if (SENSOR_I2C_DEBUG == 1)
```
Those should match the indent of the following line, our formatter doesn't automatically fix it.

2024-04-16 13:14 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +//////////////////////////////////////////////////////////////////////////////
```suggestion

```

2024-04-16 13:15 UTC, iabdalkader commented
Thanks for sending this driver! Note I have a PAG7920 and I tested it with OPENMV4P, but it's not detected, not sure why.

2024-04-17 03:00 UTC, Lak4CYUT commented
> Thanks for sending this driver! Note I have a PAG7920 and I tested it with OPENMV4P, but it's not detected, not sure why.

Not detected? Wow, I have tested with OPENMV4 before submit the PR. I will find a OPENMV4P and verify it again.

2024-04-17 07:06 UTC, iabdalkader requested changes

2024-04-17 07:06 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +#define ta_seq GRAY_QVGA
```suggestion
    #define ta_seq GRAY_QVGA
```

2024-04-17 07:06 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +#endif
```suggestion
        #if (SENSOR_I2C_DEBUG == 1)
        printf("W Reg: 0x%02X 0x%02X\r\n", ta_seq[i], ta_seq[i + 1]);
        #endif
```

And so on...

2024-04-17 07:06 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +#undef ta_seq
```suggestion
    #undef ta_seq
```

2024-04-17 07:06 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +static int reset(sensor_t *sensor) {
```suggestion

static int reset(sensor_t *sensor) {
```

2024-04-17 07:06 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +            printf("Unsupported.\r\n");
```suggestion
```

2024-04-17 07:06 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +            printf("switch bank failed, res = %d\n", res);
```suggestion
            #if (SENSOR_I2C_DEBUG == 1)
            printf("switch bank failed, res = %d\n", res);
            #endif
```

2024-04-17 07:32 UTC, Lak4CYUT commented
> I did, but it's still not detected. I can see the registers dump if I enable the debug printf, so I think the sensor I have is working. Maybe @kwagyeman can test with the RT1060.

Oops, I will check it again with a clean build, but I think the source code should be fine.
I am concerned that the sensor board you own may need a check.

By the way, how can I fetch the code that is 100% in sync with you tested? Is there a commit hash I can use? 
(Sorry, I am not very familiar with Github)

> BTW re the debug print statements, we already have something like that built-in you can just use `debug_printf` if you like. It's disabled by default, and can be enabled with:
> 
> ```c
> make -j12 TARGET=OPENMV4 DEBUG_PRINTF=1
> ```
Sure, I would very much like to follow your design. I will update my commit to fix it.

2024-04-17 08:22 UTC, iabdalkader commented
> Oops, I will check it again with a clean build, but I think the source code should be fine.
> I am concerned that the sensor board you own may need a check.

No worries, maybe Kwabena can test both the H7 and RT later today.

2024-04-17 08:24 UTC, Lak4CYUT commented
I have made a clean build using the following git command, it should align with your test environment.
```
git -c protocol.version=2 fetch --no-tags --prune --no-recurse-submodules --depth=1 upstream +597701312eac7bba9e4881a06645b7dd92abaa13:refs/remotes/pull/2199/merge
git checkout --progress --force refs/remotes/pull/2199/merge
make clean TARGET=OPENMV4 -C src
make TARGET=OPENMV4 -C src
```
It is works fine for me with OPENMV4. 
We will discuss internally how to determine whether this issue is related to the sensor board.
FYI.

2024-04-17 15:26 UTC, kwagyeman commented
Will test soon.

2024-04-18 03:32 UTC, kwagyeman commented
Hi, I tested the device on the RT1062 and OpenMV Cam H7 Plus and it works on both.

2024-04-18 03:43 UTC, Lak4CYUT commented
> Hi, I tested the device on the RT1062 and OpenMV Cam H7 Plus and it works on both.

Sounds good, so does this mean our driver is ok now?
It seems is this PR contains too many modifications, I prefer to abandon it. 
I will correct all coding style issues and resend a PR, is that ok?

2024-04-18 03:44 UTC, kwagyeman commented
Hi, you just force push update your branch. The PR will then be automatically be updated.

2024-04-18 03:47 UTC, Lak4CYUT commented
> Hi, you just force push update your branch. The PR will then be automatically be updated.

Ok, I would try it.

2024-04-18 05:05 UTC, Lak4CYUT commented
@kwagyeman 
It is seems your coding style checking system doesn't agree your suggestion XD.

That
`#define ta_seq GRAY_QVGA`
is useful for my internal development, can I keep it?

2024-04-18 06:44 UTC, iabdalkader requested changes

2024-04-18 06:44 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +const uint16_t GRAY_QVGA [][2] = {
```suggestion
// Grayscale/QVGA
static const uint16_t default_regs[][2] = {
```

2024-04-18 06:44 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +            printf("Unsupported resoultion.\n");
```suggestion
```

2024-04-18 06:44 UTC, iabdalkader commented on src/omv/sensors/pag7920.c
> +#endif
```suggestion
    debug_printf("Reg_ExpPxclkNum = %ld\n", clk_num);
```

2024-04-18 06:45 UTC, iabdalkader commented
> It seems your coding style checking bot doesn't agree with your suggestion, XD.

Yes you're right! You can revert that line to make the test pass.

> `#define ta_seq GRAY_QVGA`
> is useful for my internal development, can I keep it?

Sure.

2024-04-18 06:55 UTC, iabdalkader commented
> It seems is this PR contains too many modifications, I prefer to abandon it.

Don't worry about the commits, I will squash the PR when merging.

2024-04-18 18:55 UTC, merged