Kwabena/add genx320x320 driver
openmv/openmv pull request #2423
Opened 2024-09-23 00:03 UTC by kwagyeman

2024-09-23 07:08 UTC, iabdalkader requested changes

2024-09-23 07:08 UTC, iabdalkader commented on src/omv/common/sensor_utils.c
> +    MAIN_FB()->frame_size = MAIN_FB()->u * MAIN_FB()->v * 2;
Need to find another way.

2024-09-26 20:26 UTC, kwagyeman commented on src/omv/common/omv_i2c.h
> +int omv_i2c_writew4(omv_i2c_t *i2c, uint8_t slv_addr, uint16_t reg_addr, uint32_t reg_data);
Done

2024-09-26 20:26 UTC, kwagyeman commented on src/omv/common/sensor.h
> +        uint32_t chip_id_l;     // Sensor ID 32 bits.
Done

2024-09-27 07:36 UTC, iabdalkader approved these changes

2024-09-27 07:36 UTC, merged