GenX320: Add IOCTL for biases settings.
openmv/openmv pull request #2552
Opened 2024-12-20 14:23 UTC by nlyubova-psee

Adding functions for tuning the sensor settings/biases for particular application/conditions 
* LED or active marker
* low-light
* default 2.0.0 biases 

Adding example for LED tracking

2024-12-20 15:47 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/openmv/openmv?pullRequest=2552) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/openmv/openmv?pullRequest=2552) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/openmv/openmv?pullRequest=2552) it.</sub>

2024-12-20 17:43 UTC, kwagyeman commented
@nlyubova-psee - Please fixed the python linter issues and sign the CLA and then I will review.

2024-12-20 17:44 UTC, kwagyeman commented on scripts/examples/01-Camera/03-Event-Cameras/02-Genx320/genx320_grayscale_led_tracking.py
> +#sensor.ioctl(sensor.IOCTL_GENX320_SET_BIASES_DEFAULT_V2, 1)
Please add a comment around this as to why to uncomment it and what it does.

2024-12-20 17:44 UTC, kwagyeman commented on scripts/examples/01-Camera/03-Event-Cameras/02-Genx320/genx320_grayscale_led_tracking.py
> +#sensor.ioctl(sensor.IOCTL_GENX320_SET_BIASES_LOW_LIGHT, 1)
Please add a comment around this as to why to uncomment it and what it does.

2024-12-20 17:44 UTC, kwagyeman commented on scripts/examples/01-Camera/03-Event-Cameras/02-Genx320/genx320_grayscale_led_tracking.py
> +# This example shows off using the genx320 event camera from Prophesee.
Please expand what the script is doing exactly.

2024-12-20 17:46 UTC, kwagyeman commented on src/omv/modules/py_csi.c
> +        case OMV_CSI_IOCTL_GENX320_SET_BIASES_LOW_LIGHT:
Wrap this with:

#if (OMV_GENX320_ENABLE== 1)
...
#endif

2024-12-20 17:46 UTC, kwagyeman commented on src/omv/modules/py_csi.c
> +    { MP_ROM_QSTR(MP_QSTR_IOCTL_GENX320_SET_BIASES_ACTIVE_MARKER), MP_ROM_INT(OMV_CSI_IOCTL_GENX320_SET_BIASES_ACTIVE_MARKER)},
#if (OMV_GENX320_ENABLE== 1)
...
#endif

2024-12-20 17:47 UTC, kwagyeman commented on src/omv/sensors/genx320.c
> +        case OMV_CSI_IOCTL_GENX320_SET_BIASES_DEFAULT_V2: {
Maybe just default biases?

2024-12-20 17:49 UTC, kwagyeman requested changes
Instead of a different IOCTL per setting. Please make one IOCTL and then pass an argument enum which specifies the bias setting to apply.

See the frame size stuff in the csi module for how to create an enum in C and then make a QSTR which maps to that enum integer value.

e.g.

```
sensor.ioctl(sensor.IOCTL_GENX320_SET_BIASES, sensor.GENX320_ACTIVE_MARKER_BIASES)
```

If possible, try to make the names as short as possible for the enums since folks have to type that.

2024-12-27 08:22 UTC, iabdalkader commented
tip: The PR and commit titles should be `sensors/GenX320: Add IOCTL for biases settings.` so it gets categorized correctly.

2025-01-06 15:27 UTC, nlyubova commented on scripts/examples/01-Camera/03-Event-Cameras/02-Genx320/genx320_grayscale_led_tracking.py
> +#sensor.ioctl(sensor.IOCTL_GENX320_SET_BIASES_DEFAULT_V2, 1)
Finally, removed this line (will do a dedicated example later).

2025-01-06 15:27 UTC, nlyubova commented on scripts/examples/01-Camera/03-Event-Cameras/02-Genx320/genx320_grayscale_led_tracking.py
> +#sensor.ioctl(sensor.IOCTL_GENX320_SET_BIASES_LOW_LIGHT, 1)
Finally, removed this line (will do a dedicated example later).

2025-01-06 15:28 UTC, nlyubova commented on scripts/examples/01-Camera/03-Event-Cameras/02-Genx320/genx320_grayscale_led_tracking.py
> +# This example shows off using the genx320 event camera from Prophesee.
ok, added more info

2025-01-06 15:29 UTC, nlyubova commented on src/omv/modules/py_csi.c
> +    { MP_ROM_QSTR(MP_QSTR_IOCTL_GENX320_SET_BIASES_ACTIVE_MARKER), MP_ROM_INT(OMV_CSI_IOCTL_GENX320_SET_BIASES_ACTIVE_MARKER)},
done

2025-01-06 15:29 UTC, nlyubova commented on src/omv/sensors/genx320.c
> +        case OMV_CSI_IOCTL_GENX320_SET_BIASES_DEFAULT_V2: {
ok, renamed

2025-01-06 16:15 UTC, nlyubova-psee commented
sorry, I have occasionally used my private account to answer to this PR and it was interpreted as a review :) please remove/discard myself as a reviewer

2025-01-06 18:50 UTC, iabdalkader approved these changes

2025-01-07 07:53 UTC, kwagyeman commented
@nlyubova-psee - At CES. Will review on Saturday.

2025-01-11 20:17 UTC, kwagyeman commented
@nlyubova-psee - After addressing the error check I pointed out please rebase such that there's only one commit with text: ""sensors/GenX320: Add IOCTL for biases settings.".

2025-01-13 08:28 UTC, nlyubova-psee commented
> @nlyubova-psee - After addressing the error check I pointed out please rebase such that there's only one commit with text: "sensors/GenX320: Add IOCTL for biases settings.".

Rebased. Sorry but I cannot find the requested change. Could you please give me a hint to find it ?

2025-01-13 19:08 UTC, kwagyeman commented
@nlyubova-psee - Look good now. I'll give it a test and then approve to merge.

2025-01-14 00:04 UTC, kwagyeman approved these changes

2025-01-14 00:06 UTC, kwagyeman commented on src/omv/sensors/genx320.c
> +                }
```suggestion
                }
                default: {
                    ret = -1;
                    break;
                }
```

2025-01-14 00:07 UTC, kwagyeman commented on src/omv/sensors/genx320.c
> +                }
Though I saw this was added. Please cover this error case. Our users pass all sorts or things to functions.

2025-01-14 00:29 UTC, kwagyeman commented
Tested. Please add the error case (rebase to add it, and then it's ready to merge).

2025-01-14 18:32 UTC, kwagyeman approved these changes

2025-01-14 18:34 UTC, kwagyeman commented
@iabdalkader - This is approved to merge.

@nlyubova-psee - If prophesee would like to send a PR for improving the sensor speed from the 24MHz PCLK to 48MHz please send that now. We will have the product in stock and in the store sometime in February, I think.

2025-01-14 21:05 UTC, nlyubova-psee commented
We will try to do it next week if ok for you.

2025-01-14 21:14 UTC, kwagyeman commented
Cool

2025-01-14 21:35 UTC, merged

2025-05-06 18:27 UTC, iabdalkader commented
This pull request has been mentioned on **OpenMV Forums**. There might be relevant details there:

https://forums.openmv.io/t/genx320-bias-and-roi-setting/10980/2