Kwabena/fix rgb565 inversion 2
openmv/openmv pull request #932
Opened 2020-10-23 05:21 UTC by kwagyeman

Removes the legacy RGB565 inversion in our code base. This is now finally fixed.

This speeds up a lot of RGB565 methods since undoing the inversion doesn't have to be done anymore.
This means we can finally use STM32 hardware like DMA2D and the LCD driver.
This PR is made of 4 commits.

1st commit -> Fixes RGB565 byte reversed data coming from the cameras.
2nd commit -> Removes the old rgb2rgb table as its not the best idea...
3rd commit -> Fixes RGB565 inversion in our lookup tables.
4th commit ->Cleans up the imglib by removing all the old RGB565 methods and then fixes functions that used them.

2020-10-23 18:24 UTC, iabdalkader requested changes

2020-10-23 18:24 UTC, iabdalkader commented on src/omv/img/jpeg.c
> +            size = __REV16(size);
Please keep the macros the IM_SWAPxx macros.

2020-10-23 18:24 UTC, iabdalkader commented on src/omv/py/py_lcd.c
> +                        line[j] = COLOR_Y_TO_RGB565(pixel);
The RGB case is probably broken now.

2020-10-23 18:25 UTC, iabdalkader commented on src/omv/img/jpeg.c
> +            size = __REV16(size);
If it's not needed then please remove IM_SWAP_XX from imlib.h

2020-10-24 17:00 UTC, kwagyeman commented on src/omv/py/py_lcd.c
> +                        line[j] = COLOR_Y_TO_RGB565(pixel);
Fixed

2020-10-24 20:09 UTC, merged